In [1]:
print('hi')

hi


In [5]:
import torch
 
a=torch.arange(10)
b=torch.arange(10)
d,c=torch.cat((a,b)).unique(return_counts=True)

In [9]:
d[c==0]

tensor([], dtype=torch.int64)

In [20]:
a = torch.ones((0,))
b = torch.zeros((10,))

In [21]:
torch.arange(10)[torch.cat((a,b)).long()]

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [24]:
torch.cat((a,b),axis=0).long()

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [23]:
a.shape

torch.Size([0])

In [123]:
b

tensor([[ 5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.,
          5.,  5.,  5.],
        [ 5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.,
          5.,  5.,  5.],
        [ 5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.,
          5.,  5.,  5.],
        [ 5.,  5.,  5.,  5.,  5., 10.,  5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.,
          5.,  5.,  5.]])

In [114]:
a = torch.ones((10,17))
b = torch.ones((4,17))*5
main_index = torch.tensor([1,3,5,7])
b[3][5]=10
a[1][2]=10
a[5][2]=20


tensor([[ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
          1.,  1.,  1.],
        [ 1.,  1., 10.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
          1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
          1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
          1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
          1.,  1.,  1.],
        [ 1.,  1., 20.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
          1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
          1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
          1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
          1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1., 

In [120]:
b

tensor([[ 5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.,
          5.,  5.,  5.],
        [ 5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.,
          5.,  5.,  5.],
        [ 5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.,
          5.,  5.,  5.],
        [ 5.,  5.,  5.,  5.,  5., 10.,  5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.,
          5.,  5.,  5.]])

In [115]:
main_index.shape[0]


4

In [116]:
base_logits = a[main_index]
base_predictions, _ = base_logits.max(1,keepdim=True)
fuser_logits = b
base_predictions

tensor([[10.],
        [ 1.],
        [20.],
        [ 1.]])

In [117]:
fuser_predictions,_ = fuser_logits.max(1,keepdim=True)
fuser_predictions


tensor([[ 5.],
        [ 5.],
        [ 5.],
        [10.]])

In [103]:
mask.repeat(1,17)

tensor([[False, False, False, False, False, False, False, False, False, False,
         False, False, False, False, False, False, False],
        [ True,  True,  True,  True,  True,  True,  True,  True,  True,  True,
          True,  True,  True,  True,  True,  True,  True],
        [False, False, False, False, False, False, False, False, False, False,
         False, False, False, False, False, False, False],
        [ True,  True,  True,  True,  True,  True,  True,  True,  True,  True,
          True,  True,  True,  True,  True,  True,  True]])

In [107]:
mask.shape[0]

4

In [124]:
fuser_logits.shape[1]

17

In [137]:
a

tensor([[ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
          1.,  1.,  1.],
        [ 1.,  1., 10.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
          1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
          1.,  1.,  1.],
        [ 5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.,
          5.,  5.,  5.],
        [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
          1.,  1.,  1.],
        [ 1.,  1., 20.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
          1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
          1.,  1.,  1.],
        [ 5.,  5.,  5.,  5.,  5., 10.,  5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.,
          5.,  5.,  5.],
        [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
          1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1., 

In [146]:
import time
st = time.time()

index = torch.are_deterministic_algorithms_enabled(a.shape)
index
time.time()-st

0.00017309188842773438

In [136]:

filtered_fuser_logits = torch.tensor([[base_logits[i,j].item() if base_logits[i,j]>=fuser_logits[i,j] else fuser_logits[i,j] for j in range(base_logits.shape[1])] for i in range(base_logits.shape[0])])

In [142]:
filtered_fuser_logits
import time
("%.2f"%time.time())

'1679212615.10'

In [143]:
a[main_index] = filtered_fuser_logits.cp
a

AssertionError: Torch not compiled with CUDA enabled

In [125]:
mask = fuser_predictions>base_predictions
mask
filtered_fuser_logits = fuser_logits[mask.repeat(1,fuser_logits.shape[1])].view(filtered_main_index.shape[0],17)
filtered_fuser_logits

tensor([[ 5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.,
          5.,  5.,  5.],
        [ 5.,  5.,  5.,  5.,  5., 10.,  5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.,
          5.,  5.,  5.]])

In [126]:
index_mask = mask.squeeze(1)
filtered_main_index = main_index[index_mask]
filtered_main_index

tensor([3, 7])

In [127]:
filtered_main_index = main_index[index_mask]
filtered_main_index

tensor([3, 7])

In [139]:
a[filtered_main_index] = filtered_fuser_logits
a

RuntimeError: shape mismatch: value tensor of shape [4, 17] cannot be broadcast to indexing result of shape [2, 17]

In [97]:
filtered_fuser_logits

tensor([5., 5.])